colegio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView
from matriculas.views import Viendodocente, Viendoestudiante, Viendomatricula, Viendoperfil, Editperfil, Insertarperfil, Editdocente, Insertardocente, Editestudiante, Insertarestudiante, Editmatricula, Insertarmatricula, Elimperfil, Elimmatricula, Elimestudiante, Elimdocente



urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls), # admin site
    path('verdocente/', Viendodocente.as_view()),
    path('verestudiante/', Viendoestudiante.as_view()),
    path('vermatricula/', Viendomatricula.as_view()),
    path('verperfil/', Viendoperfil.as_view()),
    path('editperfil/<int:pk>/', Editperfil.as_view()),
    path('insertarperfil/', Insertarperfil.as_view()),
    path('editdocente/<int:pk>/', Editdocente.as_view()),
    path('insertardocente/', Insertardocente.as_view()),
    path('editestudiante/<int:pk>/', Editestudiante.as_view()),
    path('insertarestudiante/', Insertarestudiante.as_view()),
    path('editmatricula/<int:pk>/', Editmatricula.as_view()),
    path('insertarmatricula/', Insertarmatricula.as_view()),
    path('elimperfil/<int:pk>/', Elimperfil.as_view()),
    path('elimmatricula/<int:pk>/', Elimmatricula.as_view()),
    path('elimestudiante/<int:pk>/', Elimestudiante.as_view()),
    path('elimdocente/<int:pk>/', Elimdocente.as_view()),

    path ('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', LogoutView.as_view())
    path('admin/', admin.site.urls),] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)




]

matriculas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Perfil (models.Model):
    documento=models.CharField(max_length=11)
    genero=((1, "M"),
            (2, "F"),
            (3, "O"),
            )
    genero=models.SmallIntegerField(choices=genero)
    nacimiento=models.DateField()
    telefono=models.CharField(max_length=10)
    user=models.OneToOneField(User, on_delete=models.PROTECT)

    class Meta:
        db_table='perfil'

class Docente(models.Model):
     profesion=models.CharField(max_length=50)
     user=models.OneToOneField(User, on_delete=models.PROTECT)

     class Meta:
         db_table='docente'

class Estudiante(models.Model):
      observador=models.CharField(max_length=100)
      user=models.OneToOneField(User, on_delete=models.PROTECT)

      class Meta:
          db_table='estudiante'

class Matricula(models.Model):
      rh=((1, "O+"),
          (2, "A+"),
          (3, "O-"),
          (4, "AB"),)
      estados=((1, "Activo"),
               (2, "Inactivo"),)
      rh=models.SmallIntegerField(choices=rh)
      fecha=models.DateField()
      estados=models.SmallIntegerField(choices=estados)
      estudiante=models.OneToOneField(Estudiante, on_delete=models.PROTECT)
      user=models.OneToOneField(User, on_delete=models.PROTECT)


      class Meta:
          db_table='matricula'

templates/editdocente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar docente</title>
</head>
<body>
<h2>Editando Docente</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Editar">
        <input type="button" onclick="location.href='/verdocente'" value="Cancelar">
    </form>

</body>
</html>

templates/editestudiante.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar Estudiante</title>
</head>
<body>
<h2>Editando Estudiante</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Editar">
        <input type="button" onclick="location.href='/verestudiante'" value="Cancelar">
    </form>

</body>
</html>

templates/editmatricula.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar Matricula</title>
</head>
<body>
<h2>Editando Matricula</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Editar">
        <input type="button" onclick="location.href='/vermatricula'" value="Cancelar">
    </form>

</body>
</html>

templates/editperfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar Perfil</title>
</head>
<body>
    <h2>Editando Perfil</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Editar">
        <input type="button" onclick="location.href='/verperfil'" value="Cancelar">
    </form>

</body>
</html>

templates/elimdocente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eliminar docente</title>
</head>
<body>
<h2>Eliminando docente</h2>
<form action=""  method="post">

     {% csrf_token %}
    <input type="submit" value="Eliminar">
    <input type="button" onclick="location.href='/verdocente'" value="Cancelar">
</form>

</body>
</html>

templates/elimmatricula.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eliminar matricula</title>
</head>
<body>
<h2>Eliminando matricula</h2>
<form action=""  method="post">

     {% csrf_token %}
    <input type="submit" value="Eliminar">
    <input type="button" onclick="location.href='/vermatricula'" value="Cancelar">
</form>

</body>
</html>

templates/elimperfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Eliminar perfil</title>
</head>
<body>
<h2>Eliminando perfil</h2>
<form action=""  method="post">

     {% csrf_token %}
    <input type="submit" value="Eliminar">
    <input type="button" onclick="location.href='/verperfil'" value="Cancelar">
</form>

</body>
</html>

templates/insertarestudiante.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Insertar Estudiante</title>
</head>
<body>
<h2>Insertando Estudiante</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    <input type="button" onclick="location.href='/verestudiante'" value="Cancelar">
</form>
</body>
</html>

templates/insertarmatricula.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Insertar matricula</title>
</head>
<body>
<h2>Insertando Matricula</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    <input type="button" onclick="location.href='/vermatricula'" value="Cancelar">
</form>
</body>
</html>

templates/insertarperfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Insertar Perfil</title>
</head>
<body>
<h2>Insertando Perfil</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    <input type="button" onclick="location.href='/verperfil'" value="Cancelar">
</form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Iniciar sesion</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, inicial-scale=1, maximum-scale=1, minimum-scale=1">
    <link rel="stylesheet" href="estilos.css">
</head>
<body>
    <h2>Iniciando Sesion</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Iniciar Sesion">
    </form>

</body>
</html>

templates/verdocente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Viendo docente</title>
</head>
<body>
<center><h2>Docente</h2></center>

<center>
<table border="8">
    <thead>
    <tr>
        <td>Id</td>
        <td>Profesion</td>
        <td>user</td>
        {% if perms.matriculas.change_docente %}
        <td>Editar</td>
        {% endif %}
        {% if perms.matriculas.del_docente %}
        <td>Eliminar</td>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for Docente in object_list %}
        <tr>
            <td>{{ Docente.id }}</td>
            <td>{{ Docente.profesion }}</td>
            <td>{{ Docente.user }}</td>
            {% if perms.matriculas.change_docente %}
            <td><input type="button" onclick="location.href='/editdocente/{{ Docente.id }}'" value="Editar"></td>
            {% endif %}
            {% if perms.matriculas.del_docente %}
            <td><input type="button" onclick="location.href='/elimdocente/{{ Docente.id }}'" value="Eliminar"></td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</center>
<center><input type="button" onclick="location.href='/insertardocente'" value="Agregar Perfil" ></center>
<center><input type="button" onclick="location.href='/logout'" value="cerrar sesion" ></center>
</body>
</html>

templates/verestudiante.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Viendo estudiante</title>
</head>
<body>
<center><h2>Estudiante</h2></center>

<center>
<table border="8">
    <thead>
    <tr>
        <td>Id</td>
        <td>Observador</td>
        <td>user</td>
        {% if perms.matriculas.change_estudiante %}
        <td>Editar</td>
        {% endif %}
        {% if perms.matriculas.del_estudiante %}
        <td>Eliminar</td>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for Estudiante in object_list %}
        <tr>
            <td>{{ Estudiante.id }}</td>
            <td>{{ Estudiante.observador }}</td>
            <td>{{ Estudiante.user }}</td>
            {% if perms.matriculas.change_estudiante %}
            <td><input type="button" onclick="location.href='/editestudiante/{{ Estudiante.id }}'" value="Editar"></td>
            {% endif %}
            {% if perms.matriculas.del_estudiante %}
            <td><input type="button" onclick="location.href='/elimestudiante/{{ Estudiante.id }}'" value="Eliminar"></td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</center>
<center><input type="button" onclick="location.href='/insertarestudiante'" value="Agregar Estudiante" ></center>
<center><input type="button" onclick="location.href='/logout'" value="cerrar sesion" ></center>
</body>
</html>

templates/vermatricula.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Viendo Matricula</title>
</head>
<body>
<center><h2>Matricula</h2></center>

<center>
<table border="8">
    <thead>
    <tr>
        <td>Id</td>
        <td>Rh</td>
        <td>Estados</td>
        <td>Fecha</td>
        <td>Estudiante</td>
        <td>user</td>
        {% if perms.matriculas.change_matricula %}
        <td>Editar</td>
        {% endif %}
        {% if perms.matriculas.del_matricula %}
        <td>Eliminar</td>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for Matricula in object_list %}
        <tr>
            <td>{{ Matricula.id }}</td>
            <td>{{ Matricula.rh }}</td>
            <td>{{ Matricula.estados }}</td>
            <td>{{ Matricula.fecha }}</td>
            <td>{{ Matricula.estudiante }}</td>
            <td>{{ Matricula.user }}</td>
            {% if perms.matriculas.change_matricula %}
            <td><input type="button" onclick="location.href='/editmatricula/{{ Matricula.id }}'" value="Editar"></td>
            {% endif %}
            {% if perms.matriculas.del_matricula %}
            <td><input type="button" onclick="location.href='/elimmatricula/{{ Matricula.id }}'" value="Eliminar"></td>
            {% endif %}


        </tr>
    {% endfor %}
    </tbody>
</table>
</center>
<center><input type="button" onclick="location.href='/insertarmatricula'" value="Agregar matricula" ></center>
<center><input type="button" onclick="location.href='/logout'" value="cerrar sesion" ></center>
</body>
</html>